### ISSUE TITLE
Receiving lot of spam

### ISSUE THREAD

**Issue by fabiosirna** [lidofinance/lido-content#195]
Receiving lot of spam related to you blockchain project. 
I spent some time reporting these, but I'm ignored so please, take actions and protect you project.

Latest :

https://portal-lido.fi/
https://lido-distribution.fi/

Others :
https://lidofi.s3.amazonaws.com/index.html
https://distribu.s3.amazonaws.com/index.html
https://github.com/user-attachments/assets/617a45ab-f8f4-4566-a4f2-cffbef662873

**Comment by tyhonchik** [comment]
Thank you for alerting us to this issue. We are aware that scammers are actively trying to impersonate websites, and tracking all such activities and closing them can be challenging.

We strongly advise against opening any suspicious links and recommend using only official sources and URLs.
